"""
symptom_examples.py -- labeled example phrasings for each symptom class.

This is the training/reference data for the classifier fallback (classify.py):
the stdlib fuzzy backend scores a query against these, and a future offline
embedding backend will turn these into per-symptom reference vectors. They are
deliberately BROADER than the regex triggers in symptoms.py -- everyday, messy,
paraphrased ways a tuner describes the problem, including phrasings the regexes
miss on purpose (so the fallback has room to generalize).

Keep every key in sync with symptoms.TAXONOMY ids. Held-out phrases used to
MEASURE accuracy live in the eval harness (tests/test_symptoms_eval.py), never
here -- testing on the training set would lie.
"""

from __future__ import annotations

EXAMPLES = {
    "rough_idle": [
        "it idles really rough and shaky",
        "the idle bounces up and down and won't settle",
        "sitting at a light it feels lumpy and unstable",
        "rpm wanders around at idle",
        "idle is all over the place, surging in park",
        "it shakes and stumbles just sitting there",
        "can't get a steady idle, it hunts constantly",
        "the idle feels lopey and uneven when warm",
    ],
    "hesitation": [
        "it bogs down when I hit the gas",
        "there's a flat spot when I step on it",
        "stumbles off the line when I take off",
        "hesitates for a second before it pulls",
        "when I stab the throttle it falls on its face",
        "feels like it stumbles on tip-in",
        "momentary bog when I get on the pedal",
        "a dead spot right off idle when accelerating",
    ],
    "no_power": [
        "it feels really down on power",
        "sluggish and gutless up top",
        "won't pull hard like it used to",
        "runs out of breath at high rpm",
        "feels weak and lazy under acceleration",
        "just doesn't have the punch it should",
        "soft on the top end, no real pull",
        "acts like it's holding back, no power",
    ],
    "knock": [
        "I can hear it pinging under load",
        "there's a rattle when I get on it hard",
        "sounds like marbles in the engine when I accelerate",
        "detonation when I put my foot in it",
        "spark knock going up a hill",
        "it pings on pump gas at wide open",
        "a metallic rattle under heavy throttle",
        "knocking noise when it's working hard",
    ],
    "backfire": [
        "it backfires through the intake",
        "pops and bangs out the exhaust",
        "sputters and spits back when I accelerate",
        "loud bang out the tailpipe",
        "it afterfires when I let off sometimes",
        "popping through the throttle body",
        "sounds like it's coughing and backfiring",
        "misfire that pops out the exhaust",
    ],
    "runs_rich": [
        "it smells like raw gas",
        "black smoke out the tailpipe",
        "reeks of fuel and my eyes water",
        "the plugs are all sooty and black",
        "way too rich, dumping fuel",
        "exhaust is sooty and it stinks of gas",
        "fouling plugs from running rich",
        "heavy fuel smell especially at idle",
    ],
    "runs_lean": [
        "I think it's running lean",
        "the plugs look white and bleached",
        "afr is way too high, leaned out",
        "it's starving for fuel under load",
        "wideband shows lean at cruise",
        "burning lean and hot",
        "not enough fuel, running skinny",
        "lean spike when I get into it",
    ],
    "overheat": [
        "the engine runs hot",
        "temp gauge climbs and won't come down",
        "it's overheating in traffic",
        "coolant temp creeps up past normal",
        "gets really hot when I'm sitting still",
        "running warmer than it should",
        "temperature keeps rising and pegs high",
        "it boils over when it sits",
    ],
    "hard_start": [
        "it's hard to start",
        "cranks a long time before it fires",
        "takes forever to catch when I turn the key",
        "won't start without cranking and cranking",
        "have to crank it several times to get it going",
        "long crank every time, especially first thing",
        "it barely wants to fire up",
        "slow to start, cranks and cranks",
    ],
    "dies_hot": [
        "it stalls when it's hot",
        "won't restart once it's warmed up",
        "dies at a stop when the engine is hot",
        "hard to restart after it heat soaks",
        "kills itself when it gets up to temp",
        "hot start is terrible, it stumbles and dies",
        "after a drive it won't fire back up",
        "quits when hot and cranks forever to restart",
    ],
    "surge_cruise": [
        "it surges at a steady highway cruise",
        "bucks and jerks holding constant speed",
        "feels like it's lurching on the freeway",
        "won't hold a smooth cruise, it hunts",
        "rhythmic surging at part throttle",
        "the speed pulses when I'm just cruising",
        "jerking sensation at steady state",
        "it porpoises down the highway",
    ],
    "misfire": [
        "it's got a misfire",
        "feels like it's missing under load",
        "breaks up at higher rpm",
        "stutters and cuts out intermittently",
        "a skip or two when I accelerate",
        "running on what feels like seven cylinders",
        "it's breaking up and stumbling",
        "random miss that comes and goes",
    ],
    "boost_issue": [
        "it goes lean under boost",
        "boost falls flat up top",
        "the tune breaks up when the turbo spools",
        "spark blows out in boost",
        "loses fuel pressure when it makes boost",
        "runs bad once it's in boost",
        "afr goes wrong as soon as boost comes on",
        "stumbles hard when the boost hits",
    ],
    "cold_running": [
        "it runs rough until it warms up",
        "cold start it stumbles and coughs",
        "poor running when the engine is cold",
        "first thing in the morning it runs terrible",
        "rough during warmup then smooths out",
        "acts up until it reaches temp",
        "cold it's lean and hunts",
        "warmup is rough, fine once hot",
    ],
    "lugging": [
        "it lugs and chugs going up hills",
        "won't pull cleanly from low rpm",
        "chuggy and flat down low in high gear",
        "loads up when I lug it around town",
        "doesn't want to pull from the bottom end",
        "bogs and shudders when I'm lugging it",
        "no grunt at low rpm under load",
        "struggles when I let the revs drop and give it gas",
    ],
    "decel_pop": [
        "it pops and crackles when I let off",
        "exhaust burbles on deceleration",
        "crackling on overrun coming off throttle",
        "pops out the exhaust when coasting",
        "decel popping when I lift off the gas",
        "snap crackle pop when slowing down",
        "burbling and popping on the overrun",
        "it crackles every time I lift",
    ],
    "stalls_load": [
        "it dies when I put it in gear",
        "stalls when I come to a stop",
        "turning the ac on kills the idle",
        "stalls when I brake to a stop",
        "dies in drive at a red light",
        "the a/c drops the idle and it stalls",
        "quits when I slow down and stop",
        "loads down and stalls when I turn the wheel",
    ],
    "idle_hang": [
        "the rpm hangs when I let off the throttle",
        "revs stay up and are slow to come back down",
        "it won't idle back down after a blip",
        "rpm hangs at 1500 before dropping",
        "slow to return to idle when I lift",
        "the idle floats high then settles",
        "revs stick up there when I push in the clutch",
        "takes a few seconds to fall back to idle",
    ],
    "power_cut": [
        "it cuts out at high rpm",
        "hits a wall up top and won't go past it",
        "feels like it goes into limp mode",
        "power just drops out at wide open",
        "it noses over and falls flat past 6000",
        "like it hits a rev limiter early",
        "the power cuts and comes back",
        "breaks up hard on the top end and won't pull through",
    ],
    "shudder": [
        "it shudders at cruise",
        "a vibration when the converter locks up",
        "shakes at light throttle on the highway",
        "lockup shudder around 45 mph",
        "judder under light load at speed",
        "feels like a shimmy holding steady throttle",
        "torque converter shudder when locked",
        "buzzing vibration cruising down the road",
    ],
    "trans_shift": [
        "the transmission shifts really hard",
        "it bangs into gear",
        "harsh shifts and clunks",
        "won't lock the torque converter up",
        "shifting is erratic and firm",
        "slams into second every time",
        "the trans is slipping and flaring on shifts",
        "shifts too early and too soft",
    ],
    "cel": [
        "the check engine light came on",
        "it threw a code",
        "cel is on and I don't know why",
        "got a p0171 lean code",
        "service engine soon light is lit",
        "the mil is flashing",
        "set a code for lean bank one",
        "engine light popped up after the tune",
    ],
    "bad_mpg": [
        "the gas mileage is terrible",
        "it drinks fuel like crazy",
        "getting awful mpg lately",
        "fuel economy went in the toilet",
        "burning through a tank way too fast",
        "guzzling gas since I changed the tune",
        "my mileage dropped off a cliff",
        "eats fuel, horrible economy",
    ],
    "trims_drift": [
        "the fuel trims are all over the place",
        "long term trims keep climbing",
        "trims won't settle down",
        "stft is swinging wildly",
        "it re-learns and then runs worse",
        "ltft is pegged way positive",
        "trims drift around and never stabilize",
        "the correction keeps creeping up",
    ],
    "flooding": [
        "it floods when I try to start it",
        "smells flooded and won't fire",
        "loads up with fuel on startup",
        "wet plugs after cranking",
        "it's dumping fuel and washing the cylinders",
        "floods out if I don't feather the throttle",
        "cranks flooded and reeks of gas",
        "too much fuel on start, it drowns itself",
    ],
    "cold_stall": [
        "it stalls until it warms up",
        "dies when it's cold unless I hold the throttle",
        "won't stay running cold",
        "have to feather the gas until it's warm",
        "stalls out cold every morning",
        "can't idle on its own until it heats up",
        "keeps dying when cold",
        "have to nurse the throttle from a cold start",
    ],
}

# Supplementary phrasings (v0.1.26 detection expansion): more slang + paraphrase
# variety to lift the fuzzy fallback's recall, several leaning on the SYNONYMS
# map in classify.py (snail/pep/tranny/pinging...). Merged into EXAMPLES below.
# Kept distinct from the held-out eval phrases (tests/test_symptoms_eval.py).
_MORE = {
    "rough_idle": [
        "sitting in park the tach bounces around",
        "idle quality is junk, real choppy",
        "rough lopey idle when it's in park",
        "the engine shakes at idle like it's gonna stall",
        "uneven idle, feels like it's stumbling in place",
        "idle rpm sawing up and down",
    ],
    "hesitation": [
        "hesitates and hiccups when I get into it",
        "a stumble right as I roll into the throttle",
        "it bogs then catches when I punch it",
        "throttle tip-in is a mess, big stumble",
        "brief hesitation before it wakes up",
        "kind of coughs when I first give it gas",
    ],
    "no_power": [
        "it's got no pep off the line",
        "feels like it lost all its grunt",
        "no guts anymore, dog slow",
        "the get-up-and-go is gone",
        "gutless and lazy everywhere",
        "just doesn't rip like it should",
    ],
    "knock": [
        "audible knock when I lean into it",
        "it's pinking on 87",
        "hear detonation climbing a hill",
        "rattling under load like pre-ignition",
        "spark knock at part throttle",
        "light ping when the engine's loaded",
    ],
    "backfire": [
        "it backfires through the intake on a hard pull",
        "pops and bangs out the tailpipe",
        "spits back through the throttle body",
        "loud exhaust bang on shifts",
        "coughs and sputters at part throttle",
        "afterfire pop when I get off it",
    ],
    "runs_rich": [
        "the tailpipe is black and sooty",
        "smells super rich at idle",
        "it's pig rich, reeks of fuel",
        "plugs are carbon fouled",
        "dumping way too much fuel",
        "gassy smell and black smoke",
    ],
    "runs_lean": [
        "it's leaning out up top",
        "afr swings lean under load",
        "the mixture is too skinny",
        "plugs are chalky white",
        "wideband shows it going lean",
        "starving for fuel at wot",
    ],
    "overheat": [
        "it's cooking itself in traffic",
        "coolant temp climbing toward the red",
        "runs hot and the fans can't keep up",
        "boiling over when I sit",
        "temperature just keeps rising",
        "gets way too hot on a hot day",
    ],
    "hard_start": [
        "takes a long crank to catch",
        "have to crank it a bunch before it lights",
        "it's a hard starter cold and hot",
        "cranks forever then finally fires",
        "slow to start every single time",
        "needs extra cranking before it fires up",
    ],
    "dies_hot": [
        "heat soak kills it, won't restart",
        "dies at a light once it's hot",
        "hot restart is a nightmare",
        "quits when it gets up to temp",
        "after shutdown it won't fire back up warm",
        "stalls out when the engine's fully hot",
    ],
    "surge_cruise": [
        "won't stop hunting on the interstate",
        "bucks at a steady 60",
        "porpoises holding light throttle",
        "cruise speed pulses in and out",
        "lurching sensation at constant speed",
        "won't cruise smooth, keeps surging",
    ],
    "misfire": [
        "feels like a cylinder is dropping out",
        "breaking up bad under load",
        "intermittent miss at higher rpm",
        "stutters like it's misfiring",
        "running rough like a dead hole",
        "random misfire that comes and goes",
    ],
    "boost_issue": [
        "goes lean the second it's on the snail",
        "boost comes on and it falls apart",
        "spark blowout under boost",
        "fuel pressure drops when boosted",
        "runs terrible once the turbo lights",
        "afr craps out in boost",
    ],
    "cold_running": [
        "rough as a cob on a cold morning",
        "cold it stumbles and coughs",
        "cold-blooded, needs a minute to wake up",
        "acts up during warmup then clears",
        "won't run right until it heats up",
        "poor cold driveability first thing",
    ],
    "lugging": [
        "it lugs and chugs in high gear",
        "no low-end grunt under load",
        "bogs when I lug it around town",
        "chuggy pulling from low rpm",
        "struggles to pull when the revs drop",
        "loads up lugging up a grade",
    ],
    "decel_pop": [
        "crackles and pops when I lift off",
        "burbles on the overrun",
        "exhaust snap crackle pop on decel",
        "pops coming off the throttle",
        "decel burble every time I let off",
        "it crackles slowing down",
    ],
    "stalls_load": [
        "stalls the second it drops into gear",
        "ac on and the idle dies",
        "dies coasting to a stop",
        "stalls when I brake at a light",
        "loads down and quits turning the wheel",
        "in drive at a stop it wants to stall",
    ],
    "idle_hang": [
        "the revs hang when I let off",
        "rpm floats and takes forever to drop",
        "won't settle back to idle after a blip",
        "throttle hangs up around 1500",
        "slow to fall back to idle",
        "revs stick up there off throttle",
    ],
    "power_cut": [
        "power just cuts out at wot",
        "hits a brick wall up top",
        "feels like limp mode kicks in",
        "drops flat past six grand",
        "power falls off a cliff at high rpm",
        "it noses over and quits pulling",
    ],
    "shudder": [
        "converter shudder at part throttle",
        "shakes cruising around 45",
        "lockup judder on the highway",
        "vibration when it locks up",
        "buzzy shudder holding steady",
        "shimmy feeling at light cruise",
    ],
    "trans_shift": [
        "the trans bangs into gear",
        "harsh clunky shifts",
        "won't lock the converter",
        "slushbox shifts way too firm",
        "flares between gears",
        "the tranny is slipping on the 2-3",
    ],
    "cel": [
        "check engine light popped on",
        "threw a lean code",
        "got a p0300 misfire code",
        "mil is on after the tune",
        "service engine soon light lit up",
        "it set a couple of codes",
    ],
    "bad_mpg": [
        "gas mileage tanked",
        "it's drinking fuel",
        "terrible economy since the swap",
        "guzzling gas now",
        "burning through a tank fast",
        "my mpg fell off a cliff",
    ],
    "trims_drift": [
        "fuel trims keep climbing",
        "ltft won't stabilize",
        "the corrections drift all over",
        "trims never settle",
        "it relearns and runs worse",
        "long term trims pegged positive",
    ],
    "flooding": [
        "floods out cranking cold",
        "loads up with fuel on start",
        "wet plugs after it won't start",
        "smells flooded when I try to fire it",
        "dumps fuel and won't catch",
        "drowns itself starting",
    ],
    "cold_stall": [
        "have to feather it cold or it dies",
        "won't idle on its own when cold",
        "dies from a cold start",
        "keeps stalling until temp comes up",
        "nurse the throttle till it's warm",
        "cold and it won't hold an idle",
    ],
}

for _sid, _phrases in _MORE.items():
    EXAMPLES[_sid].extend(_phrases)

